PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus = " fan-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus = " thermal-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus = " power-supply-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus = " events-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus2600 = " fan-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus2600 = " thermal-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus2600 = " power-supply-policy"
PHOSPHOR_DBUS_MONITOR_CONFIGS_append_romulus2600 = " events-policy"
